### ISSUE TITLE
No permission in singleplayer world

### ISSUE THREAD

**Issue by Melishy** [MeowCraftMC/NBTEdit#50]
I can't seem to edit nbt using this mod, it says that I do not have a permission, and commands aren't showing, just saying "unknown command".
I don't know how can I fix that issue, but I need help with this.

![Image](https://github.com/user-attachments/assets/d0c819ed-f68e-4dc6-ab02-f6256f74a970)

**Comment by Melishy** [comment]
_after 2 minutes, someone has created the issue with the exact topic... (#51) that's so crazy_

**Comment by qyl27** [comment]
Oh, yes, that's my mistake.  
In the last version `5.2.10`, I have added a compat of `fabric-permission-api` by lucko. But I haven't used it before, it has no way to determine if the permission manager really exists.  
If you have some mods like `spark` installed, it will need a permission manager.  
I have fixed it and used vanilla permission levels as a fallback in 5.2.11.

**Comment by Melishy** [comment]
Well, the issue still remains. I am getting the error when clicking **N**, or running any **/nbtedit** command.
```
[16:03:02] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: 'net.minecraft.class_2168 net.minecraft.class_1297.method_5671()'
	at knot/me.lucko.fabric.api.permissions.v0.Permissions.check(Permissions.java:175) ~[fabric-permissions-api-v0-0.2-SNAPSHOT-4dccd28795ed08cf.jar:?]
	at knot/cx.rain.mc.nbtedit.fabric.command.FabricPermissionApiImpl.hasPermission(FabricPermissionApiImpl.java:25) ~[nbtedit-fabric-5.2.11.jar:?]
	at knot/cx.rain.mc.nbtedit.api.command.IModPermission.canOpenEditor(IModPermission.java:13) ~[nbtedit-fabric-5.2.11.jar:?]
	at knot/cx.rain.mc.nbtedit.networking.NetworkingHelper.checkReadPermission(NetworkingHelper.java:12) ~[nbtedit-fabric-5.2.11.jar:?]
	at knot/cx.rain.mc.nbtedit.networking.NetworkEditingHelper.lambda$editItemStack$2(NetworkEditingHelper.java:86) ~[nbtedit-fabric-5.2.11.jar:?]
	at knot/net.minecraft.class_3738.run(class_3738.java:18) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_18859(class_1255.java:164) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:889) ~[client-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:180) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_16075(class_1255.java:138) ~[client-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:871) ~[client-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:865) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_18857(class_1255.java:147) ~[client-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_18857(MinecraftServer.java:829) ~[client-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:836) ~[client-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:719) ~[client-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:292) ~[client-intermediary.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

**Comment by qyl27** [comment]
Oh, yes. Something used the ver 0.2 of `fabric-permissions-api`. Would you like to provide the loaded mods list? (The logs which printed on starting, start with `Loading xxx mods:`).  
As far as I know, version 0.2 is not for Minecraft over 1.20.1. (We work with 0.3.x.)

**Comment by Melishy** [comment]
Here are my mods list:

![Image](https://github.com/user-attachments/assets/8e17eecb-b1a7-4854-abf3-82540c79c90e)

![Image](https://github.com/user-attachments/assets/236aee21-0a19-41c0-9997-b6813c00b216)

![Image](https://github.com/user-attachments/assets/28e22102-9fb0-4ae4-aaff-6e2ff302df69)

![Image](https://github.com/user-attachments/assets/b8ff1fa8-6469-4f3c-9669-36bd59243f6a)

**Comment by Melishy** [comment]
Oh, yes, and logs: https://0x0.st/8XxF.txt

**Comment by qyl27** [comment]
Ah, thank you.  
In the log, it is caused by the mod named `Do a Barrel Roll`. This issue was noticed and reported to them 2 weeks ago (https://github.com/enjarai/do-a-barrel-roll/issues/188). You can remove it for now or install some mod like `spark` (or `luckperms` on the server-side), they provided the correct version and will cover the bad one.

**Comment by Melishy** [comment]
I see. Thank you.
